[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
rslib = { path = "../rslib" }
clap = { version = "4.5.31", features = ["derive"] }
console = "0.15.11"
indicatif = "0.17.11"
wax = "0.6.0"
anyhow = "1.0.97"
rayon = "1.10.0"
env_logger = "0.11"
log = "0.4"
